//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class practicespEntities : DbContext
    {
        public practicespEntities()
            : base("name=practicespEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int prcEmployDelete(Nullable<int> empno)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcEmployDelete", empnoParameter);
        }
    
        public virtual int prcEmployInsert(ObjectParameter empno, string name, string gender, string dept, string desig, Nullable<int> basic)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var deptParameter = dept != null ?
                new ObjectParameter("dept", dept) :
                new ObjectParameter("dept", typeof(string));
    
            var desigParameter = desig != null ?
                new ObjectParameter("desig", desig) :
                new ObjectParameter("desig", typeof(string));
    
            var basicParameter = basic.HasValue ?
                new ObjectParameter("basic", basic) :
                new ObjectParameter("basic", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcEmployInsert", empno, nameParameter, genderParameter, deptParameter, desigParameter, basicParameter);
        }
    
        public virtual int prcEmployOutExample(Nullable<int> empno, ObjectParameter name, ObjectParameter gender, ObjectParameter dept, ObjectParameter desig, ObjectParameter basic)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcEmployOutExample", empnoParameter, name, gender, dept, desig, basic);
        }
    
        public virtual ObjectResult<prcEmploySearch_Result> prcEmploySearch(Nullable<int> empno)
        {
            var empnoParameter = empno.HasValue ?
                new ObjectParameter("empno", empno) :
                new ObjectParameter("empno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcEmploySearch_Result>("prcEmploySearch", empnoParameter);
        }
    
        public virtual ObjectResult<prcEmployShow_Result> prcEmployShow()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcEmployShow_Result>("prcEmployShow");
        }
    }
}
